### ISSUE TITLE
Chapter 10 - tuples

### ISSUE THREAD

**Issue by joaovitorsilvestre** [victorjabur/py4inf-ptBR#19]
I just wanna know,  someone have already did some work in this chapter? Because I'll start doing the translation of chapter 10 to finish all them.

**Comment by victorjabur** [comment]
Hello @joaovitorsilvestre You can start the translation as soon as possible, it's dedicated for you. It's the last pending chapter of this translation work. Go ahead and take some fun. Thank you.
